// Auto-generated by start-dev.sh on Пт 15 мая 2026 22:15:34 MSK
import { Platform } from 'react-native';

const DEV_HOST = Platform.OS === 'android' ? '192.168.1.38' : 'localhost';

const ENV = {
  development: {
    API_BASE_URL: `http://${DEV_HOST}:3000`,
  },
  production: {
    API_BASE_URL: 'https://sovereign-back.igroteh.su',
  },
};

const currentEnv = __DEV__ ? 'development' : 'production';

export const CONFIG = ENV[currentEnv];
